import { clickerText as tx } from '../../i18n';
import type { SvgLayerDocument, SvgLayersSettings } from './model';

function esc(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] || character);
}

function rgbHex(rgb: [number, number, number]): string {
  return `#${rgb.map((value) => value.toString(16).padStart(2, '0')).join('')}`;
}

export function renderSvgLayers(settings: SvgLayersSettings): string {
  return `<div class="svg-layers-shell">
    <header class="svg-layers-topbar"><a class="svg-layers-back" href="#/admin">← ${tx('Dashboard', 'Bảng điều khiển')}</a><div class="svg-layers-brand"><span class="svg-layers-mark">S</span><div><span>FORMAFORGE / CLICKER</span><strong>${tx('SVG Layers', 'Tách lớp SVG')}</strong></div></div><div class="svg-layers-badge">${tx('Admin workspace', 'Workspace admin')}</div></header>
    <main class="svg-layers-main">
      <section class="svg-layers-stage"><div id="svgLayersViewport" class="svg-layers-viewport"></div><div id="svgLayersEmpty" class="svg-layers-empty"><div class="svg-layers-empty-mark">S</div><h2>${tx('Separate one SVG into printable layers', 'Tách một SVG thành các lớp có thể in')}</h2><p>${tx('Import an SVG, then click the head and petals to assign them to Top or Base.', 'Nhập SVG, sau đó bấm vào phần đầu và cánh hoa để gán làm Top hoặc Base.')}</p></div><div id="svgLayersStatus" class="svg-layers-status">${tx('Waiting for an SVG', 'Đang chờ tệp SVG')}</div></section>
      <aside class="svg-layers-sidebar">
        <div class="svg-layers-heading"><span class="svg-layers-eyebrow">${tx('SVG LAYERS / CLICKER', 'SVG LAYERS / CLICKER')}</span><h1>${tx('Split SVG artwork', 'Tách lớp hình SVG')}</h1><p>${tx('A dedicated workflow for separating a top area from an outer base. Image and Image + Blocks are unchanged.', 'Quy trình riêng để tách phần top và phần base bên ngoài. Image và Image + Blocks không bị thay đổi.')}</p></div>
        <section class="svg-layers-card"><div class="svg-layers-card-title">${tx('1 · Import SVG', '1 · Nhập SVG')}</div><label id="svgLayersDrop" class="svg-layers-drop"> <strong>${tx('Drop an SVG here', 'Thả SVG vào đây')}</strong><span>${tx('or click to choose a file', 'hoặc bấm để chọn tệp')}</span><input id="svgLayersFile" type="file" accept=".svg,image/svg+xml" /></label><div id="svgLayersFileName" class="svg-layers-help">${tx('Supports grouped paths, shapes and fills.', 'Hỗ trợ path, shape và group có màu.')}</div></section>
        <section class="svg-layers-card"><div class="svg-layers-card-title">${tx('2 · Select regions', '2 · Chọn khu vực')}</div><div id="svgLayersPreview" class="svg-layers-preview"><span>${tx('The imported SVG preview appears here.', 'SVG sau khi nhập sẽ xuất hiện ở đây.')}</span></div><div id="svgLayersList" class="svg-layers-list"><p class="svg-layers-help">${tx('Import an SVG to see selectable regions.', 'Nhập SVG để xem các vùng có thể chọn.')}</p></div><div class="svg-layers-assignment"><button type="button" class="svg-layers-assign" data-assign="top">↑ ${tx('Assign selected to Top', 'Gán vùng chọn làm Top')}</button><button type="button" class="svg-layers-assign" data-assign="base">↓ ${tx('Assign selected to Base', 'Gán vùng chọn làm Base')}</button><button type="button" class="svg-layers-assign ghost" data-assign="none">× ${tx('Clear assignment', 'Bỏ gán')}</button></div></section>
        <section class="svg-layers-card"><div class="svg-layers-card-title">${tx('3 · Geometry', '3 · Hình học')}</div><label class="svg-layers-field"><span>${tx('Overall size', 'Kích thước tổng thể')} <output id="svgLayersSizeValue">${settings.targetSizeMm.toFixed(0)} mm</output></span><input id="svgLayersSize" type="range" min="20" max="120" step="1" value="${settings.targetSizeMm}" /></label><label class="svg-layers-field"><span>${tx('Base depth', 'Độ dày Base')} <output id="svgLayersBaseDepthValue">${settings.baseDepthMm.toFixed(1)} mm</output></span><input id="svgLayersBaseDepth" type="range" min="0.8" max="12" step="0.1" value="${settings.baseDepthMm}" /></label><label class="svg-layers-field"><span>${tx('Top depth', 'Độ dày Top')} <output id="svgLayersTopDepthValue">${settings.topDepthMm.toFixed(1)} mm</output></span><input id="svgLayersTopDepth" type="range" min="0.4" max="10" step="0.1" value="${settings.topDepthMm}" /></label><label class="svg-layers-field"><span>${tx('Top lift', 'Độ nâng Top')} <output id="svgLayersTopOffsetValue">${settings.topOffsetMm.toFixed(2)} mm</output></span><input id="svgLayersTopOffset" type="range" min="0" max="2" step="0.05" value="${settings.topOffsetMm}" /></label><div class="svg-layers-color-row"><label>${tx('Base color', 'Màu Base')}<input id="svgLayersBaseColor" type="color" value="${rgbHex(settings.baseColor)}" /></label><label>${tx('Top color', 'Màu Top')}<input id="svgLayersTopColor" type="color" value="${rgbHex(settings.topColor)}" /></label></div><label class="svg-layers-check"><input id="svgLayersSourceColors" type="checkbox" checked /> <span>${tx('Keep source colors on Top', 'Giữ màu gốc cho Top')}</span></label></section>
        <section class="svg-layers-card svg-layers-export"><div class="svg-layers-card-title">${tx('4 · Export', '4 · Xuất file')}</div><div class="svg-layers-help">${tx('Top and Base remain separate printable parts.', 'Top và Base được giữ thành các phần riêng để in.')}</div><div class="svg-layers-export-grid"><button id="svgLayersExport3mf" type="button" disabled>3MF</button><button id="svgLayersExportStl" type="button" disabled>STL</button></div><button id="svgLayersReset" type="button" class="svg-layers-reset">${tx('Reset workspace', 'Đặt lại workspace')}</button></section>
      </aside>
    </main>
  </div>`;
}

export function renderSvgLayerList(doc: SvgLayerDocument | null, selectedId: string | null): string {
  if (!doc) return `<p class="svg-layers-help">${tx('Import an SVG to see selectable regions.', 'Nhập SVG để xem các vùng có thể chọn.')}</p>`;
  if (!doc.layers.length) return `<p class="svg-layers-help">${tx('No selectable vector regions found.', 'Không tìm thấy vùng vector có thể chọn.')}</p>`;
  return doc.layers.map((layer) => `<div class="svg-layers-row ${layer.id === selectedId ? 'selected' : ''}" data-svg-layer="${esc(layer.id)}"><button class="svg-layers-row-main" type="button" data-select-layer="${esc(layer.id)}"><span class="svg-layers-swatch" style="background:${rgbHex(layer.color)}"></span><span><strong>${esc(layer.label)}</strong><small>${layer.isBackground ? tx('Background candidate', 'Có thể là nền') : `${layer.pathIndexes.length} ${tx('path(s)', 'path')}`}</small></span></button><span class="svg-layers-role ${layer.assignment}">${layer.assignment === 'top' ? 'TOP' : layer.assignment === 'base' ? 'BASE' : '—'}</span></div>`).join('');
}
