import { zipSync } from 'fflate';
import { getClickerDocument } from '../../../runtime';
import type { ClickerPart } from '../../../types';
import { sanitizeMesh } from '../../../export/meshUtils';

type StlVertex = [number, number, number];

function writeStlTriangle(view: DataView, offset: number, v1: StlVertex, v2: StlVertex, v3: StlVertex) {
  const abx = v2[0] - v1[0];
  const aby = v2[1] - v1[1];
  const abz = v2[2] - v1[2];
  const acx = v3[0] - v1[0];
  const acy = v3[1] - v1[1];
  const acz = v3[2] - v1[2];
  const nx = aby * acz - abz * acy;
  const ny = abz * acx - abx * acz;
  const nz = abx * acy - aby * acx;
  const length = Math.hypot(nx, ny, nz);
  const normal = length > 1e-12 ? [nx / length, ny / length, nz / length] : [0, 0, 0];

  view.setFloat32(offset, normal[0], true);
  view.setFloat32(offset + 4, normal[1], true);
  view.setFloat32(offset + 8, normal[2], true);
  offset += 12;
  for (const vertex of [v1, v2, v3]) {
    view.setFloat32(offset, vertex[0], true);
    view.setFloat32(offset + 4, vertex[1], true);
    view.setFloat32(offset + 8, vertex[2], true);
    offset += 12;
  }
  view.setUint16(offset, 0, true);
  return offset + 2;
}

/** Build one STL while preserving the reference assembly origin. */
export function buildSTLObject(rawParts: ClickerPart[], referenceParts = rawParts): Uint8Array {
  const parts = rawParts.map(sanitizeMesh);
  const reference = referenceParts.map(sanitizeMesh);
  let minX = Infinity;
  let minY = Infinity;
  let minZ = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const part of reference) {
    for (let i = 0; i < part.vertProperties.length; i += part.numProp) {
      minX = Math.min(minX, part.vertProperties[i]);
      minY = Math.min(minY, part.vertProperties[i + 1]);
      minZ = Math.min(minZ, part.vertProperties[i + 2]);
      maxX = Math.max(maxX, part.vertProperties[i]);
      maxY = Math.max(maxY, part.vertProperties[i + 1]);
    }
  }
  if (!isFinite(minX)) minX = minY = minZ = maxX = maxY = 0;
  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2;
  let totalTriangles = 0;
  for (const part of parts) totalTriangles += part.triVerts.length / 3;

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode('Generated by FormaForgeDT MultiColor (OBJECT STL Export)');
  for (let i = 0; i < headerBytes.length && i < 80; i++) view.setUint8(i, headerBytes[i]);
  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const part of parts) {
    for (let i = 0; i < part.triVerts.length; i += 3) {
      const getVertex = (vertexIndex: number): StlVertex => {
        const index = vertexIndex * part.numProp;
        return [
          part.vertProperties[index] - centerX,
          part.vertProperties[index + 1] - centerY,
          part.vertProperties[index + 2] - minZ,
        ];
      };
      offset = writeStlTriangle(
        view,
        offset,
        getVertex(part.triVerts[i]),
        getVertex(part.triVerts[i + 1]),
        getVertex(part.triVerts[i + 2]),
      );
    }
  }
  return new Uint8Array(buffer);
}

function downloadStlArchive(bytes: Uint8Array, fileName: string) {
  const blob = new Blob([bytes as unknown as BlobPart], { type: 'application/zip' });
  const url = URL.createObjectURL(blob);
  const anchor = getClickerDocument().createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  getClickerDocument().body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Download Base and each named color layer as independent printable STLs. */
export function downloadSTLObjectsZip(parts: ClickerPart[], fileName = 'multi-color.stl') {
  const groups = new Map<string, ClickerPart[]>();
  for (const part of parts) {
    const key = part.name || (part.group === 'base' ? 'base' : 'layer');
    groups.set(key, [...(groups.get(key) ?? []), part]);
  }

  const usedNames = new Set<string>();
  const files: Record<string, Uint8Array> = {};
  for (const [key, groupedParts] of groups) {
    const safeName = key.replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '') || 'object';
    let stem = safeName;
    let suffix = 2;
    while (usedNames.has(`${stem}.stl`)) stem = `${safeName}-${suffix++}`;
    usedNames.add(`${stem}.stl`);
    // STL has no colour/material channel, so the ZIP contains one object per
    // colour. Use one shared origin for every file so importing them together
    // preserves the assembled XY/Z stack.
    files[`${stem}.stl`] = buildSTLObject(groupedParts, parts);
  }

  const stem = fileName.replace(/\.stl$/i, '') || 'multi-color';
  downloadStlArchive(zipSync(files, { level: 6 }), `${stem}-objects-stl.zip`);
}
