import { getClickerDocument } from '../runtime';
// src/export/stlExport.ts
import type { ClickerPart } from '../types';
import { sanitizeMesh, groupBBox } from './meshUtils';

export type StlGroup = 'base' | 'top';

export function buildSTL(rawParts: ClickerPart[]): Uint8Array {
  // Äi qua bá»™ lá»c lÃ m sáº¡ch lÆ°á»›i 3D
  const parts = rawParts.map(sanitizeMesh);

  let minZ = Infinity;
  for (const p of parts) {
    for (let i = 2; i < p.vertProperties.length; i += p.numProp) {
      if (p.vertProperties[i] < minZ) minZ = p.vertProperties[i];
    }
  }
  if (!isFinite(minZ)) minZ = 0;

  const baseBB = groupBBox(parts, 'base', minZ);
  const topBB = groupBBox(parts, 'top', minZ);

  const GAP_MM = 5;
  const baseWidth = isFinite(baseBB.maxX) ? baseBB.maxX - baseBB.minX : 0;
  const topWidth = isFinite(topBB.maxX) ? topBB.maxX - topBB.minX : 0;
  
  const baseCenterX = isFinite(baseBB.minX) ? (baseBB.minX + baseBB.maxX) / 2 : 0;
  const topCenterX = isFinite(topBB.minX) ? (topBB.minX + topBB.maxX) / 2 : 0;

  const tx = baseCenterX + baseWidth / 2 + GAP_MM + topWidth / 2 - topCenterX;
  const topCenterY = isFinite(topBB.minY) ? (topBB.minY + topBB.maxY) / 2 : 0;
  const ty = 2 * topCenterY;
  const tz = topBB.maxZ;

  let totalTriangles = 0;
  for (const p of parts) {
    totalTriangles += p.triVerts.length / 3;
  }

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);

  const encoder = new TextEncoder();
  const headerText = "Generated by FormaForgeDT Clicker Generator (STL Export)";
  const headerBytes = encoder.encode(headerText);
  for (let i = 0; i < headerBytes.length && i < 80; i++) {
    view.setUint8(i, headerBytes[i]);
  }

  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const p of parts) {
    const isTop = p.group === 'top';
    const vp = p.vertProperties;
    const tv = p.triVerts;
    const np = p.numProp;

    for (let i = 0; i < tv.length; i += 3) {
      const idx1 = tv[i] * np;
      const idx2 = tv[i + 1] * np;
      const idx3 = tv[i + 2] * np;

      const getVertex = (idx: number) => {
        let x = vp[idx];
        let y = vp[idx + 1];
        let z = vp[idx + 2] - minZ;

        if (isTop) {
          x = x + tx;
          y = -y + ty;
          z = -z + tz;
        }
        return [x, y, z];
      };

      const v1 = getVertex(idx1);
      const v2 = getVertex(idx2);
      const v3 = getVertex(idx3);

      view.setFloat32(offset, 0, true);
      view.setFloat32(offset + 4, 0, true);
      view.setFloat32(offset + 8, 0, true);
      offset += 12;

      view.setFloat32(offset, v1[0], true);
      view.setFloat32(offset + 4, v1[1], true);
      view.setFloat32(offset + 8, v1[2], true);
      offset += 12;

      view.setFloat32(offset, v2[0], true);
      view.setFloat32(offset + 4, v2[1], true);
      view.setFloat32(offset + 8, v2[2], true);
      offset += 12;

      view.setFloat32(offset, v3[0], true);
      view.setFloat32(offset + 4, v3[1], true);
      view.setFloat32(offset + 8, v3[2], true);
      offset += 12;

      view.setUint16(offset, 0, true);
      offset += 2;
    }
  }

  return new Uint8Array(buffer);
}

/**
 * Build one printable STL from one logical part of the model.
 *
 * The combined exporter above keeps the historical exploded layout. Split
 * exports are normalized independently so each downloaded piece starts at
 * Z=0 and is centered on its own XY bounds.
 */
export function buildSTLPart(rawParts: ClickerPart[], group: StlGroup): Uint8Array {
  const parts = rawParts.filter((part) => part.group === group).map(sanitizeMesh);
  let minZ = Infinity;
  for (const part of parts) {
    for (let i = 2; i < part.vertProperties.length; i += part.numProp) {
      if (part.vertProperties[i] < minZ) minZ = part.vertProperties[i];
    }
  }
  if (!isFinite(minZ)) minZ = 0;

  const bb = groupBBox(parts, group, minZ);
  const centerX = isFinite(bb.minX) && isFinite(bb.maxX) ? (bb.minX + bb.maxX) / 2 : 0;
  const centerY = isFinite(bb.minY) && isFinite(bb.maxY) ? (bb.minY + bb.maxY) / 2 : 0;
  const maxZ = isFinite(bb.maxZ) ? bb.maxZ : 0;

  let totalTriangles = 0;
  for (const part of parts) totalTriangles += part.triVerts.length / 3;

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode(
    `Generated by FormaForgeDT Clicker Generator (${group.toUpperCase()} STL Export)`,
  );
  for (let i = 0; i < headerBytes.length && i < 80; i++) view.setUint8(i, headerBytes[i]);
  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const part of parts) {
    const vp = part.vertProperties;
    const tv = part.triVerts;
    const np = part.numProp;

    const getVertex = (vertexIndex: number) => {
      const index = vertexIndex * np;
      const sourceX = vp[index];
      const sourceY = vp[index + 1];
      const sourceZ = vp[index + 2] - minZ;

      // Flip the top onto its underside so it can be printed face-up as a
      // separate piece, matching the orientation of the legacy combined STL.
      return [
        sourceX - centerX,
        group === 'top' ? -sourceY + 2 * centerY : sourceY - centerY,
        group === 'top' ? maxZ - sourceZ : sourceZ,
      ];
    };

    for (let i = 0; i < tv.length; i += 3) {
      const v1 = getVertex(tv[i]);
      const v2 = getVertex(tv[i + 1]);
      const v3 = getVertex(tv[i + 2]);

      view.setFloat32(offset, 0, true);
      view.setFloat32(offset + 4, 0, true);
      view.setFloat32(offset + 8, 0, true);
      offset += 12;

      for (const vertex of [v1, v2, v3]) {
        view.setFloat32(offset, vertex[0], true);
        view.setFloat32(offset + 4, vertex[1], true);
        view.setFloat32(offset + 8, vertex[2], true);
        offset += 12;
      }

      view.setUint16(offset, 0, true);
      offset += 2;
    }
  }

  return new Uint8Array(buffer);
}

function downloadStlBytes(bytes: Uint8Array, fileName: string) {
  const blob = new Blob([bytes as unknown as BlobPart], { type: 'model/stl' });
  const url = URL.createObjectURL(blob);
  const a = getClickerDocument().createElement('a');
  a.href = url;
  a.download = fileName;
  getClickerDocument().body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadSTL(parts: ClickerPart[], fileName = 'clicker.stl') {
  downloadStlBytes(buildSTL(parts), fileName);
}

/** Download the base and top as separate STL files. */
export function downloadSTLSplit(parts: ClickerPart[], fileName = 'clicker.stl') {
  const stem = fileName.replace(/\.stl$/i, '') || 'clicker';
  const groups: StlGroup[] = ['base', 'top'];

  for (const group of groups) {
    if (!parts.some((part) => part.group === group)) continue;
    downloadStlBytes(buildSTLPart(parts, group), `${stem}-${group}.stl`);
  }
}


