import { getClickerDocument } from '../runtime';
// src/export/stlExport.ts
import { strToU8, zipSync } from 'fflate';
import type { ClickerPart, RGB } from '../types';
import { sanitizeMesh, groupBBox } from './meshUtils';

export type StlGroup = 'base' | 'top';
type StlVertex = [number, number, number];

function writeStlTriangle(view: DataView, offset: number, v1: StlVertex, v2: StlVertex, v3: StlVertex) {
  const abx = v2[0] - v1[0];
  const aby = v2[1] - v1[1];
  const abz = v2[2] - v1[2];
  const acx = v3[0] - v1[0];
  const acy = v3[1] - v1[1];
  const acz = v3[2] - v1[2];
  const nx = aby * acz - abz * acy;
  const ny = abz * acx - abx * acz;
  const nz = abx * acy - aby * acx;
  const length = Math.hypot(nx, ny, nz);
  const normal = length > 1e-12 ? [nx / length, ny / length, nz / length] : [0, 0, 0];

  view.setFloat32(offset, normal[0], true);
  view.setFloat32(offset + 4, normal[1], true);
  view.setFloat32(offset + 8, normal[2], true);
  offset += 12;

  for (const vertex of [v1, v2, v3]) {
    view.setFloat32(offset, vertex[0], true);
    view.setFloat32(offset + 4, vertex[1], true);
    view.setFloat32(offset + 8, vertex[2], true);
    offset += 12;
  }

  view.setUint16(offset, 0, true);
  return offset + 2;
}

export function buildSTL(rawParts: ClickerPart[]): Uint8Array {
  // Äi qua bá»™ lá»c lÃ m sáº¡ch lÆ°á»›i 3D
  const parts = rawParts.map(sanitizeMesh);

  let minZ = Infinity;
  for (const p of parts) {
    for (let i = 2; i < p.vertProperties.length; i += p.numProp) {
      if (p.vertProperties[i] < minZ) minZ = p.vertProperties[i];
    }
  }
  if (!isFinite(minZ)) minZ = 0;

  const baseBB = groupBBox(parts, 'base', minZ);
  const topBB = groupBBox(parts, 'top', minZ);

  const GAP_MM = 5;
  const baseWidth = isFinite(baseBB.maxX) ? baseBB.maxX - baseBB.minX : 0;
  const topWidth = isFinite(topBB.maxX) ? topBB.maxX - topBB.minX : 0;
  
  const baseCenterX = isFinite(baseBB.minX) ? (baseBB.minX + baseBB.maxX) / 2 : 0;
  const topCenterX = isFinite(topBB.minX) ? (topBB.minX + topBB.maxX) / 2 : 0;

  const tx = baseCenterX + baseWidth / 2 + GAP_MM + topWidth / 2 - topCenterX;
  const topCenterY = isFinite(topBB.minY) ? (topBB.minY + topBB.maxY) / 2 : 0;
  const ty = 2 * topCenterY;
  const tz = topBB.maxZ;

  let totalTriangles = 0;
  for (const p of parts) {
    totalTriangles += p.triVerts.length / 3;
  }

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);

  const encoder = new TextEncoder();
  const headerText = "Generated by FormaForgeDT Clicker Generator (STL Export)";
  const headerBytes = encoder.encode(headerText);
  for (let i = 0; i < headerBytes.length && i < 80; i++) {
    view.setUint8(i, headerBytes[i]);
  }

  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const p of parts) {
    const isTop = p.group === 'top';
    const vp = p.vertProperties;
    const tv = p.triVerts;
    const np = p.numProp;

    for (let i = 0; i < tv.length; i += 3) {
      const idx1 = tv[i] * np;
      const idx2 = tv[i + 1] * np;
      const idx3 = tv[i + 2] * np;

      const getVertex = (idx: number): StlVertex => {
        let x = vp[idx];
        let y = vp[idx + 1];
        let z = vp[idx + 2] - minZ;

        if (isTop) {
          x = x + tx;
          y = -y + ty;
          z = -z + tz;
        }
        return [x, y, z];
      };

      const v1 = getVertex(idx1);
      const v2 = getVertex(idx2);
      const v3 = getVertex(idx3);

      offset = writeStlTriangle(view, offset, v1, v2, v3);
    }
  }

  return new Uint8Array(buffer);
}

/**
 * Build one printable STL from one logical part of the model.
 *
 * The combined exporter above keeps the historical exploded layout. Split
 * exports are normalized independently so each downloaded piece starts at
 * Z=0 and is centered on its own XY bounds.
 */
export function buildSTLPart(rawParts: ClickerPart[], group: StlGroup): Uint8Array {
  const parts = rawParts.filter((part) => part.group === group).map(sanitizeMesh);
  let minZ = Infinity;
  for (const part of parts) {
    for (let i = 2; i < part.vertProperties.length; i += part.numProp) {
      if (part.vertProperties[i] < minZ) minZ = part.vertProperties[i];
    }
  }
  if (!isFinite(minZ)) minZ = 0;

  const bb = groupBBox(parts, group, minZ);
  const centerX = isFinite(bb.minX) && isFinite(bb.maxX) ? (bb.minX + bb.maxX) / 2 : 0;
  const centerY = isFinite(bb.minY) && isFinite(bb.maxY) ? (bb.minY + bb.maxY) / 2 : 0;
  const maxZ = isFinite(bb.maxZ) ? bb.maxZ : 0;

  let totalTriangles = 0;
  for (const part of parts) totalTriangles += part.triVerts.length / 3;

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode(
    `Generated by FormaForgeDT Clicker Generator (${group.toUpperCase()} STL Export)`,
  );
  for (let i = 0; i < headerBytes.length && i < 80; i++) view.setUint8(i, headerBytes[i]);
  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const part of parts) {
    const vp = part.vertProperties;
    const tv = part.triVerts;
    const np = part.numProp;

    const getVertex = (vertexIndex: number): StlVertex => {
      const index = vertexIndex * np;
      const sourceX = vp[index];
      const sourceY = vp[index + 1];
      const sourceZ = vp[index + 2] - minZ;

      // Flip the top onto its underside so it can be printed face-up as a
      // separate piece, matching the orientation of the legacy combined STL.
      return [
        sourceX - centerX,
        group === 'top' ? -sourceY + 2 * centerY : sourceY - centerY,
        group === 'top' ? maxZ - sourceZ : sourceZ,
      ];
    };

    for (let i = 0; i < tv.length; i += 3) {
      const v1 = getVertex(tv[i]);
      const v2 = getVertex(tv[i + 1]);
      const v3 = getVertex(tv[i + 2]);

      offset = writeStlTriangle(view, offset, v1, v2, v3);
    }
  }

  return new Uint8Array(buffer);
}

/**
 * Build one STL without moving it away from the generated assembly.
 *
 * Every material STL uses the bounds of `referenceParts`, so importing all
 * files from the ZIP at once restores the exact same XY/Z placement as the
 * Clicker preview. This is deliberately different from `buildSTLPart`, which
 * flips and normalizes the two legacy printable pieces independently.
 */
export function buildSTLAtSharedOrigin(
  rawParts: ClickerPart[],
  referenceParts: ClickerPart[] = rawParts,
): Uint8Array {
  const parts = rawParts.map(sanitizeMesh);
  const reference = referenceParts.map(sanitizeMesh);
  let minX = Infinity;
  let minY = Infinity;
  let minZ = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  for (const part of reference) {
    for (let i = 0; i < part.vertProperties.length; i += part.numProp) {
      minX = Math.min(minX, part.vertProperties[i]);
      minY = Math.min(minY, part.vertProperties[i + 1]);
      minZ = Math.min(minZ, part.vertProperties[i + 2]);
      maxX = Math.max(maxX, part.vertProperties[i]);
      maxY = Math.max(maxY, part.vertProperties[i + 1]);
    }
  }
  if (!isFinite(minX)) minX = minY = minZ = maxX = maxY = 0;

  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2;
  let totalTriangles = 0;
  for (const part of parts) totalTriangles += part.triVerts.length / 3;

  const buffer = new ArrayBuffer(84 + totalTriangles * 50);
  const view = new DataView(buffer);
  const headerBytes = new TextEncoder().encode(
    'Generated by FormaForgeDT Clicker (MATERIAL STL Export)',
  );
  for (let i = 0; i < headerBytes.length && i < 80; i++) view.setUint8(i, headerBytes[i]);
  view.setUint32(80, totalTriangles, true);

  let offset = 84;
  for (const part of parts) {
    const getVertex = (vertexIndex: number): StlVertex => {
      const index = vertexIndex * part.numProp;
      return [
        part.vertProperties[index] - centerX,
        part.vertProperties[index + 1] - centerY,
        part.vertProperties[index + 2] - minZ,
      ];
    };
    for (let i = 0; i < part.triVerts.length; i += 3) {
      offset = writeStlTriangle(
        view,
        offset,
        getVertex(part.triVerts[i]),
        getVertex(part.triVerts[i + 1]),
        getVertex(part.triVerts[i + 2]),
      );
    }
  }

  return new Uint8Array(buffer);
}

function materialKey(rgb: RGB): string {
  return rgb.map((value) => Math.max(0, Math.min(255, Math.round(value)))).join(',');
}

function materialHex(rgb: RGB): string {
  return rgb
    .map((value) => Math.max(0, Math.min(255, Math.round(value))).toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Build a slicer-ready archive with one STL per unique filament colour.
 * Disconnected meshes sharing a colour intentionally live in the same STL;
 * STL has no material channel, so the filename and manifest carry that data.
 */
export function buildSTLMaterialsZip(parts: ClickerPart[]): Uint8Array {
  const printableParts = parts.filter((part) => part.triVerts.length >= 3);
  const groups = new Map<string, { rgb: RGB; parts: ClickerPart[] }>();
  for (const part of printableParts) {
    const key = materialKey(part.colorRgb);
    const group = groups.get(key);
    if (group) group.parts.push(part);
    else groups.set(key, { rgb: part.colorRgb, parts: [part] });
  }

  const files: Record<string, Uint8Array> = {};
  const materials = [...groups.values()].map((group, index) => {
    const file = `filament-${String(index + 1).padStart(2, '0')}-${materialHex(group.rgb)}.stl`;
    files[file] = buildSTLAtSharedOrigin(group.parts, printableParts);
    return {
      slot: index + 1,
      file,
      rgb: group.rgb,
      parts: group.parts.map((part) => part.name),
    };
  });

  files['materials.json'] = strToU8(JSON.stringify({
    format: 'FormaForgeDT Clicker multi-material STL ZIP',
    units: 'millimeter',
    placement: 'shared-origin',
    materials,
  }, null, 2));

  return zipSync(files, { level: 6 });
}

function downloadStlBytes(bytes: Uint8Array, fileName: string) {
  const blob = new Blob([bytes as unknown as BlobPart], { type: 'model/stl' });
  const url = URL.createObjectURL(blob);
  const a = getClickerDocument().createElement('a');
  a.href = url;
  a.download = fileName;
  getClickerDocument().body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadSTL(parts: ClickerPart[], fileName = 'clicker.stl') {
  downloadStlBytes(buildSTL(parts), fileName);
}

/** Download the base and top as one archive with exactly two printable files. */
export function downloadSTLSplit(parts: ClickerPart[], fileName = 'clicker.stl') {
  const stem = fileName.replace(/\.stl$/i, '') || 'clicker';
  const archive = zipSync({
    'base.stl': buildSTLPart(parts, 'base'),
    'top.stl': buildSTLPart(parts, 'top'),
  }, { level: 6 });
  const blob = new Blob([archive as unknown as BlobPart], { type: 'application/zip' });
  const url = URL.createObjectURL(blob);
  const a = getClickerDocument().createElement('a');
  a.href = url;
  a.download = `${stem}-stl.zip`;
  getClickerDocument().body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Download one shared-origin STL per unique filament colour. */
export function downloadSTLMaterialsZip(parts: ClickerPart[], fileName = 'clicker.stl') {
  const stem = fileName.replace(/\.stl$/i, '') || 'clicker';
  const blob = new Blob([buildSTLMaterialsZip(parts) as unknown as BlobPart], { type: 'application/zip' });
  const url = URL.createObjectURL(blob);
  const a = getClickerDocument().createElement('a');
  a.href = url;
  a.download = `${stem}-multicolor-stl.zip`;
  getClickerDocument().body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}


