import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, Check, RefreshCw, Sparkles } from 'lucide-react';
import type { Order, OrderStatus, Product } from '@hometown/types';
import { formatVnd } from './lib/cart';
import { authConfigured, getAccessToken, getCurrentUser, signInAdmin, signOutAdmin } from './lib/supabase';
import { apiConfigured, getAdminGeometry, getAdminOverview, getAdminSettings, getProducts, listAdminOrders, updateAdminOrderStatus, updateAdminSettings, type AdminGeometry, type AdminOverview, type AdminSettings } from './lib/api';
import { localizedColorName, localizedStatus, localizedStockStatus, useI18n } from './lib/i18n';
import { GlassButton } from './components/Shell';
import { ClickerWorkspacePage } from './ClickerWorkspacePage';

const tabs = ['Overview', 'Orders', 'Products', 'Geometry', 'Clicker', 'Settings'] as const;
const orderStatuses: OrderStatus[] = ['PENDING', 'CONFIRMED', 'IN_PRODUCTION', 'SHIPPED', 'COMPLETED', 'CANCELLED'];
type Tab = typeof tabs[number];
function asSettingsForm(settings: AdminSettings) { return { shop_name: settings.shop_name, email: settings.email ?? '', phone: settings.phone ?? '', website: settings.website ?? '', address: settings.address ?? '' }; }

export function AdminWorkspacePage() {
  const { t, language } = useI18n();
  const [user, setUser] = useState<import('@supabase/supabase-js').User | null>(null); const [loading, setLoading] = useState(true);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState(''); const [signingIn, setSigningIn] = useState(false);
  const [tab, setTab] = useState<Tab>('Overview'); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false); const [overview, setOverview] = useState<AdminOverview | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [products, setProducts] = useState<Product[]>([]); const [geometry, setGeometry] = useState<AdminGeometry | null>(null); const [settingsForm, setSettingsForm] = useState({ shop_name: '', email: '', phone: '', website: '', address: '' }); const [settingsSaving, setSettingsSaving] = useState(false); const [updatingOrderId, setUpdatingOrderId] = useState('');
  useEffect(() => { getCurrentUser().then(setUser).finally(() => setLoading(false)); }, []);
  const loadData = async (target: Tab = tab) => { const token = await getAccessToken(); if (!token) throw new Error(t('common.sessionExpired')); if (target === 'Overview') setOverview(await getAdminOverview(token)); if (target === 'Orders') setOrders(await listAdminOrders(token)); if (target === 'Products') { const [catalog, summary] = await Promise.all([getProducts(), getAdminOverview(token)]); setProducts(catalog); setOverview(summary); } if (target === 'Geometry') setGeometry(await getAdminGeometry(token)); if (target === 'Settings') setSettingsForm(asSettingsForm(await getAdminSettings(token))); };
  useEffect(() => { if (!user) return; setRefreshing(true); setError(''); void loadData(tab).catch((requestError) => setError(requestError instanceof Error ? requestError.message : t('common.error'))).finally(() => setRefreshing(false)); }, [user, tab]);
  const refresh = () => { setRefreshing(true); setError(''); void loadData(tab).catch((requestError) => setError(requestError instanceof Error ? requestError.message : t('common.error'))).finally(() => setRefreshing(false)); };
  const changeStatus = async (id: string, status: OrderStatus) => { setUpdatingOrderId(id); setError(''); try { const token = await getAccessToken(); if (!token) throw new Error(t('common.sessionExpired')); const updated = await updateAdminOrderStatus(id, status, token); setOrders((current) => current.map((order) => order.id === updated.id ? updated : order)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : t('common.error')); } finally { setUpdatingOrderId(''); } };
  const saveSettings = async (event: FormEvent) => { event.preventDefault(); setSettingsSaving(true); setError(''); try { const token = await getAccessToken(); if (!token) throw new Error(t('common.sessionExpired')); await updateAdminSettings(settingsForm, token); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : t('common.error')); } finally { setSettingsSaving(false); } };
  if (loading) return <div className="container page-section empty-state"><Sparkles /><p>{t('auth.loading')}</p></div>;
  if (!user) return <div className="container page-section admin-login"><span className="eyebrow">{t('admin.eyebrow')}</span><h1><span>{t('admin.title').split(' ')[0]}<br /><i>{t('admin.title').split(' ').slice(1).join(' ')}</i></span></h1><p>{authConfigured ? t('admin.loginHint') : t('admin.notConfigured')}</p>{authConfigured && <form className="admin-login-form" onSubmit={async (event) => { event.preventDefault(); setLoginError(''); setSigningIn(true); try { setUser(await signInAdmin(email, password)); } catch (signInError) { setLoginError(signInError instanceof Error ? signInError.message : t('auth.invalid')); } finally { setSigningIn(false); } }}><label>{t('auth.email')}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>{t('auth.password')}<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{loginError && <div className="error-box">{loginError}</div>}<GlassButton className="full-width" disabled={signingIn}>{signingIn ? t('admin.signingIn') : t('admin.signIn')} <ArrowRight size={16} /></GlassButton></form>}</div>;
  return <div className="container page-section admin-page"><div className="admin-header"><div><span className="eyebrow">{t('admin.eyebrow')}</span><h1>{t('admin.title')}</h1><p>{user.email}</p></div><div className="admin-header-actions"><span className="admin-badge"><span className="live-dot" /> {apiConfigured ? t('admin.live') : t('admin.apiMissing')}</span><button className="text-link" onClick={() => { void signOutAdmin().then(() => setUser(null)); }}>{t('admin.signOut')}</button></div></div><div className="admin-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{t(`admin.${item.toLowerCase()}`)}</button>)}</div>{error && <div className="error-box admin-error">{error}</div>}<div className="admin-toolbar"><span className="eyebrow">{t(`admin.${tab.toLowerCase()}`)} / {t('admin.liveData')}</span><button className="glass-button" onClick={refresh} disabled={refreshing}><RefreshCw size={14} /> {refreshing ? t('admin.refreshing') : t('admin.refresh')}</button></div>{tab === 'Overview' && <OverviewPanel overview={overview} />}{tab === 'Orders' && <OrdersPanel orders={orders} updatingOrderId={updatingOrderId} onStatus={changeStatus} language={language} />}{tab === 'Products' && <ProductsPanel products={products} />}{tab === 'Geometry' && <GeometryPanel geometry={geometry} />}{tab === 'Clicker' && <ClickerPanel />}{tab === 'Settings' && <SettingsPanel form={settingsForm} saving={settingsSaving} onChange={(key, value) => setSettingsForm((current) => ({ ...current, [key]: value }))} onSubmit={saveSettings} />}</div>;
}

function OverviewPanel({ overview }: { overview: AdminOverview | null }) { const { t } = useI18n(); if (!overview) return <div className="admin-placeholder"><Sparkles /><p>{t('admin.loading')}</p></div>; const metrics = [[t('admin.orders'), overview.orders], [t('admin.products'), overview.products], ['Collections', overview.collections], ['Design projects', overview.designProjects], ['Lamp designs', overview.lampDesigns], ['Email logs', overview.emailLogs]]; return <section className="admin-metric-grid">{metrics.map(([label, value]) => <div className="admin-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>; }
function OrdersPanel({ orders, updatingOrderId, onStatus, language }: { orders: Order[]; updatingOrderId: string; onStatus: (id: string, status: OrderStatus) => void; language: 'en' | 'vi' }) { const { t } = useI18n(); return orders.length ? <div className="admin-table"><div className="table-head admin-order-grid"><span>{t('admin.order')}</span><span>{t('admin.customer')}</span><span>{t('admin.status')}</span><span>{t('admin.total')}</span><span>{t('admin.items')}</span></div>{orders.map((order) => <div className="table-row admin-order-grid" key={order.id}><div><strong>#{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleString(language === 'vi' ? 'vi-VN' : 'en-US')}</small></div><div><strong>{order.customer.name}</strong><small>{order.customer.email}</small></div><select aria-label={`${t('admin.status')} ${order.orderNumber}`} value={order.status} disabled={updatingOrderId === order.id} onChange={(event) => onStatus(order.id, event.target.value as OrderStatus)}>{orderStatuses.map((status) => <option value={status} key={status}>{localizedStatus(status, t)}</option>)}</select><strong>{formatVnd(order.total)}</strong><span>{t('common.items', { count: order.items.length })}</span></div>)}</div> : <div className="admin-placeholder"><Sparkles /><h3>{t('admin.noOrdersTitle')}</h3><p>{t('admin.noOrdersText')}</p></div>; }
function ProductsPanel({ products }: { products: Product[] }) { const { t } = useI18n(); return products.length ? <div className="admin-table"><div className="table-head admin-product-grid"><span>{t('admin.sku')}</span><span>{t('admin.product')}</span><span>{t('admin.products')}</span><span>{t('admin.total')}</span><span>{t('admin.stock')}</span></div>{products.map((product) => <div className="table-row admin-product-grid" key={product.id}><strong>{product.sku}</strong><div><strong>{product.name}</strong><small>{product.category}</small></div><span>{product.collection}</span><strong>{formatVnd(product.price)}</strong><span className="status-pill processing">{localizedStockStatus(product.stockStatus, t)}</span></div>)}</div> : <div className="admin-placeholder"><Sparkles /><h3>{t('admin.noProductsTitle')}</h3><p>{t('admin.noProductsText')}</p></div>; }
function GeometryPanel({ geometry }: { geometry: AdminGeometry | null }) { const { t } = useI18n(); if (!geometry) return <div className="admin-placeholder"><Sparkles /><p>{t('admin.loading')}</p></div>; return <div className="admin-geometry-grid"><section className="admin-table"><div className="table-head"><span>{t('admin.project')}</span><span>{t('admin.version')}</span><span>{t('admin.autosaved')}</span></div>{geometry.projects.length ? geometry.projects.map((project) => <div className="table-row" key={project.id}><strong>{project.name}</strong><span>{project.version}</span><small>{new Date(project.autosaved_at).toLocaleString()}</small></div>) : <div className="admin-placeholder"><Check /><p>{t('admin.noProjects')}</p></div>}</section><section className="admin-table"><div className="table-head"><span>{t('admin.lampDesign')}</span><span>{t('admin.version')}</span><span>{t('admin.status')}</span></div>{geometry.lampDesigns.length ? geometry.lampDesigns.map((design) => <div className="table-row" key={design.id}><strong>{design.product_id ?? t('admin.unassigned')}</strong><span>{design.version}</span><span className="status-pill">{design.published ? t('admin.published') : t('admin.draft')}</span></div>) : <div className="admin-placeholder"><Check /><p>{t('admin.noDesigns')}</p></div>}</section></div>; }
function ClickerPanel() { const { t } = useI18n(); const features = ['Image', 'Svg', 'Icon', 'Text', 'Blocks', 'Hybrid', 'Flex', 'Exports', 'Projects']; return <section className="clicker-admin-panel"><div className="clicker-admin-intro"><div><span className="eyebrow">{t('admin.clickerEyebrow')}</span><h2>{t('admin.clickerTitle')}</h2><p>{t('admin.clickerDescription')}</p></div><span className="clicker-local-badge">{t('admin.clickerLocal')}</span></div><div className="clicker-feature-grid">{features.map((feature) => <span className="clicker-feature-pill" key={feature}>{t(`admin.clicker${feature}`)}</span>)}</div><div className="clicker-embed-head"><span className="eyebrow">{t('admin.clickerEmbedded')}</span><span className="clicker-local-badge">{t('admin.clickerSource')}</span></div><div className="clicker-embed"><ClickerWorkspacePage labels={{ clicker: t('admin.clicker'), flexKeychain: t('admin.clickerFlexKeychain'), flexOrganizer: t('admin.clickerFlexOrganizer') }} /></div></section>; }
function SettingsPanel({ form, saving, onChange, onSubmit }: { form: { shop_name: string; email: string; phone: string; website: string; address: string }; saving: boolean; onChange: (key: keyof SettingsPanelProps['form'], value: string) => void; onSubmit: (event: FormEvent) => void }) { const { t } = useI18n(); return <form className="admin-settings-form" onSubmit={onSubmit}><label>{t('admin.shopName')}<input required value={form.shop_name} onChange={(event) => onChange('shop_name', event.target.value)} /></label><label>{t('account.email')}<input type="email" value={form.email} onChange={(event) => onChange('email', event.target.value)} /></label><label>{t('account.phone')}<input value={form.phone} onChange={(event) => onChange('phone', event.target.value)} /></label><label>{t('admin.website')}<input type="url" value={form.website} onChange={(event) => onChange('website', event.target.value)} /></label><label className="wide">{t('account.address')}<textarea value={form.address} onChange={(event) => onChange('address', event.target.value)} /></label><GlassButton disabled={saving}>{saving ? t('admin.saving') : t('admin.saveSettings')} <Check size={15} /></GlassButton></form>; }
type SettingsPanelProps = Parameters<typeof SettingsPanel>[0];
