import { useEffect, useState } from 'react';
import { ArrowRight, Check, RefreshCw, Sparkles } from 'lucide-react';
import type { Order, OrderStatus, Product } from '@hometown/types';
import { formatVnd } from './lib/cart';
import { authConfigured, getAccessToken, getCurrentUser, signInAdmin, signOutAdmin } from './lib/supabase';
import { apiConfigured, getAdminGeometry, getAdminOverview, getAdminSettings, getProducts, listAdminOrders, updateAdminOrderStatus, updateAdminSettings, type AdminGeometry, type AdminOverview, type AdminSettings } from './lib/api';
import { GlassButton } from './components/Shell';

const tabs = ['Overview', 'Orders', 'Products', 'Geometry', 'Settings'] as const;
const orderStatuses: OrderStatus[] = ['PENDING', 'CONFIRMED', 'IN_PRODUCTION', 'SHIPPED', 'COMPLETED', 'CANCELLED'];
type Tab = typeof tabs[number];

function statusLabel(status: OrderStatus) { return status.replace('IN_PRODUCTION', 'IN PRODUCTION'); }
function asSettingsForm(settings: AdminSettings) { return { shop_name: settings.shop_name, email: settings.email ?? '', phone: settings.phone ?? '', website: settings.website ?? '', address: settings.address ?? '' }; }

export function AdminWorkspacePage() {
  const [user, setUser] = useState<import('@supabase/supabase-js').User | null>(null);
  const [loading, setLoading] = useState(true);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState(''); const [signingIn, setSigningIn] = useState(false);
  const [tab, setTab] = useState<Tab>('Overview'); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const [overview, setOverview] = useState<AdminOverview | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [products, setProducts] = useState<Product[]>([]); const [geometry, setGeometry] = useState<AdminGeometry | null>(null); const [settings, setSettings] = useState<AdminSettings | null>(null);
  const [settingsForm, setSettingsForm] = useState({ shop_name: '', email: '', phone: '', website: '', address: '' }); const [settingsSaving, setSettingsSaving] = useState(false); const [updatingOrderId, setUpdatingOrderId] = useState('');

  useEffect(() => { getCurrentUser().then(setUser).finally(() => setLoading(false)); }, []);

  const loadData = async (target: Tab = tab) => {
    const token = await getAccessToken();
    if (!token) throw new Error('Phiên đăng nhập đã hết hạn.');
    if (target === 'Overview') setOverview(await getAdminOverview(token));
    if (target === 'Orders') setOrders(await listAdminOrders(token));
    if (target === 'Products') { const [catalog, summary] = await Promise.all([getProducts(), getAdminOverview(token)]); setProducts(catalog); setOverview(summary); }
    if (target === 'Geometry') setGeometry(await getAdminGeometry(token));
    if (target === 'Settings') { const nextSettings = await getAdminSettings(token); setSettings(nextSettings); setSettingsForm(asSettingsForm(nextSettings)); }
  };
  useEffect(() => { if (!user) return; setRefreshing(true); setError(''); void loadData(tab).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Không thể tải dữ liệu studio.')).finally(() => setRefreshing(false)); }, [user, tab]);
  const refresh = () => { setRefreshing(true); setError(''); void loadData(tab).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Không thể tải dữ liệu studio.')).finally(() => setRefreshing(false)); };
  const changeStatus = async (id: string, status: OrderStatus) => { setUpdatingOrderId(id); setError(''); try { const token = await getAccessToken(); if (!token) throw new Error('Phiên đăng nhập đã hết hạn.'); const updated = await updateAdminOrderStatus(id, status, token); setOrders((current) => current.map((order) => order.id === updated.id ? updated : order)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Không thể cập nhật đơn hàng.'); } finally { setUpdatingOrderId(''); } };
  const saveSettings = async (event: React.FormEvent) => { event.preventDefault(); setSettingsSaving(true); setError(''); try { const token = await getAccessToken(); if (!token) throw new Error('Phiên đăng nhập đã hết hạn.'); const nextSettings = await updateAdminSettings(settingsForm, token); setSettings(nextSettings); setSettingsForm(asSettingsForm(nextSettings)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Không thể cập nhật settings.'); } finally { setSettingsSaving(false); } };

  if (loading) return <div className="container page-section empty-state"><Sparkles /><p>Checking studio access…</p></div>;
  if (!user) return <div className="container page-section admin-login"><span className="eyebrow">STUDIO / AUTHENTICATED ACCESS</span><h1>Control<br /><i>room.</i></h1><p>{authConfigured ? 'Sign in with a Supabase account assigned the ADMIN role.' : 'Supabase Auth is not configured in this build. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable studio access.'}</p>{authConfigured && <form className="admin-login-form" onSubmit={async (event) => { event.preventDefault(); setLoginError(''); setSigningIn(true); try { setUser(await signInAdmin(email, password)); } catch (signInError) { setLoginError(signInError instanceof Error ? signInError.message : 'Đăng nhập thất bại.'); } finally { setSigningIn(false); } }}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{loginError && <div className="error-box">{loginError}</div>}<GlassButton className="full-width" disabled={signingIn}>{signingIn ? 'Signing in…' : 'Sign in to studio'} <ArrowRight size={16} /></GlassButton></form>}</div>;

  return <div className="container page-section admin-page"><div className="admin-header"><div><span className="eyebrow">STUDIO / AUTHENTICATED</span><h1>Control room.</h1><p>{user.email}</p></div><div className="admin-header-actions"><span className="admin-badge"><span className="live-dot" /> {apiConfigured ? 'LIVE STUDIO' : 'API NOT CONFIGURED'}</span><button className="text-link" onClick={() => { void signOutAdmin().then(() => setUser(null)); }}>Sign out</button></div></div><div className="admin-tabs">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>{error && <div className="error-box admin-error">{error}</div>}<div className="admin-toolbar"><span className="eyebrow">{tab} / LIVE DATA</span><button className="glass-button" onClick={refresh} disabled={refreshing}><RefreshCw size={14} /> {refreshing ? 'Refreshing…' : 'Refresh'}</button></div>{tab === 'Overview' && <OverviewPanel overview={overview} />}{tab === 'Orders' && <OrdersPanel orders={orders} updatingOrderId={updatingOrderId} onStatus={changeStatus} />}{tab === 'Products' && <ProductsPanel products={products} />}{tab === 'Geometry' && <GeometryPanel geometry={geometry} />}{tab === 'Settings' && <SettingsPanel form={settingsForm} saving={settingsSaving} onChange={(key, value) => setSettingsForm((current) => ({ ...current, [key]: value }))} onSubmit={saveSettings} />}</div>;
}

function OverviewPanel({ overview }: { overview: AdminOverview | null }) { if (!overview) return <div className="admin-placeholder"><Sparkles /><p>Loading studio metrics…</p></div>; const metrics = [['Orders', overview.orders], ['Products', overview.products], ['Collections', overview.collections], ['Design projects', overview.designProjects], ['Lamp designs', overview.lampDesigns], ['Email logs', overview.emailLogs]]; return <section className="admin-metric-grid">{metrics.map(([label, value]) => <div className="admin-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>; }
function OrdersPanel({ orders, updatingOrderId, onStatus }: { orders: Order[]; updatingOrderId: string; onStatus: (id: string, status: OrderStatus) => void }) { return orders.length ? <div className="admin-table"><div className="table-head admin-order-grid"><span>ORDER</span><span>CUSTOMER</span><span>STATUS</span><span>TOTAL</span><span>ITEMS</span></div>{orders.map((order) => <div className="table-row admin-order-grid" key={order.id}><div><strong>#{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleString('vi-VN')}</small></div><div><strong>{order.customer.name}</strong><small>{order.customer.email}</small></div><select aria-label={`Status ${order.orderNumber}`} value={order.status} disabled={updatingOrderId === order.id} onChange={(event) => onStatus(order.id, event.target.value as OrderStatus)}>{orderStatuses.map((status) => <option value={status} key={status}>{statusLabel(status)}</option>)}</select><strong>{formatVnd(order.total)}</strong><span>{order.items.length} item{order.items.length === 1 ? '' : 's'}</span></div>)}</div> : <div className="admin-placeholder"><Sparkles /><h3>No orders yet.</h3><p>New order requests will appear here after checkout connects to the API.</p></div>; }
function ProductsPanel({ products }: { products: Product[] }) { return products.length ? <div className="admin-table"><div className="table-head admin-product-grid"><span>SKU</span><span>PRODUCT</span><span>COLLECTION</span><span>PRICE</span><span>STOCK</span></div>{products.map((product) => <div className="table-row admin-product-grid" key={product.id}><strong>{product.sku}</strong><div><strong>{product.name}</strong><small>{product.category}</small></div><span>{product.collection}</span><strong>{formatVnd(product.price)}</strong><span className="status-pill processing">{product.stockStatus}</span></div>)}</div> : <div className="admin-placeholder"><Sparkles /><h3>No published products.</h3><p>Publish a product in Supabase to make it available in the storefront.</p></div>; }
function GeometryPanel({ geometry }: { geometry: AdminGeometry | null }) { if (!geometry) return <div className="admin-placeholder"><Sparkles /><p>Loading geometry projects…</p></div>; return <div className="admin-geometry-grid"><section className="admin-table"><div className="table-head"><span>PROJECT</span><span>VERSION</span><span>AUTOSAVED</span></div>{geometry.projects.length ? geometry.projects.map((project) => <div className="table-row" key={project.id}><strong>{project.name}</strong><span>{project.version}</span><small>{new Date(project.autosaved_at).toLocaleString('vi-VN')}</small></div>) : <div className="admin-placeholder"><Check /><p>No saved design projects.</p></div>}</section><section className="admin-table"><div className="table-head"><span>LAMP DESIGN</span><span>VERSION</span><span>STATUS</span></div>{geometry.lampDesigns.length ? geometry.lampDesigns.map((design) => <div className="table-row" key={design.id}><strong>{design.product_id ?? 'Unassigned'}</strong><span>{design.version}</span><span className="status-pill">{design.published ? 'PUBLISHED' : 'DRAFT'}</span></div>) : <div className="admin-placeholder"><Check /><p>No saved lamp designs.</p></div>}</section></div>; }
function SettingsPanel({ form, saving, onChange, onSubmit }: { form: { shop_name: string; email: string; phone: string; website: string; address: string }; saving: boolean; onChange: (key: keyof SettingsPanelProps['form'], value: string) => void; onSubmit: (event: React.FormEvent) => void }) { return <form className="admin-settings-form" onSubmit={onSubmit}><label>Shop name<input required value={form.shop_name} onChange={(event) => onChange('shop_name', event.target.value)} /></label><label>Email<input type="email" value={form.email} onChange={(event) => onChange('email', event.target.value)} /></label><label>Phone<input value={form.phone} onChange={(event) => onChange('phone', event.target.value)} /></label><label>Website<input type="url" value={form.website} onChange={(event) => onChange('website', event.target.value)} /></label><label className="wide">Address<textarea value={form.address} onChange={(event) => onChange('address', event.target.value)} /></label><GlassButton disabled={saving}>{saving ? 'Saving…' : 'Save shop settings'} <Check size={15} /></GlassButton></form>; }
type SettingsPanelProps = Parameters<typeof SettingsPanel>[0];
