import { clickerText as rawTx } from '../../i18n';
import type { VectorizerSettings } from './model';

function tx(english: string, vietnamese: string): string {
  const value = rawTx(english, vietnamese);
  if (!/[ÃÂÄÅÆáàâäåæçèéêëìíîïðñòóôõöùúûüýÿƒ]/.test(value)) return value;
  const bytes = Uint8Array.from(value, (character) => character === 'ƒ' ? 0x83 : character.charCodeAt(0) & 0xff);
  return new TextDecoder().decode(bytes);
}

function rgbHex(rgb: [number, number, number]): string {
  return `#${rgb.map((value) => value.toString(16).padStart(2, '0')).join('')}`;
}

export function renderImageVectorizer(settings: VectorizerSettings): string {
  return `<div class="iv-shell">
    <header class="iv-topbar"><a class="iv-back" href="#/admin">← ${tx('Dashboard', 'Bảng điều khiển')}</a><div class="iv-brand"><span class="iv-brand-mark">V</span><div><span>FORMAFORGE / CLICKER</span><strong>${tx('Image Vectorizer', 'Chuyển ảnh thành SVG')}</strong></div></div><div class="iv-topbar-meta">${tx('Local processing · SVG output', 'Xử lý trên máy · xuất SVG')}</div></header>
    <main class="iv-main">
      <section class="iv-pane iv-input-pane">
        <div class="iv-pane-toolbar"><div class="iv-pane-title"><span class="iv-pane-icon">↙</span><strong>${tx('Input', 'Đầu vào')}</strong><small id="ivInputDimensions">${tx('No image loaded', 'Chưa có ảnh')}</small></div><div class="iv-toolbar-actions"><button type="button" data-zoom-input="out">−</button><button type="button" data-zoom-input="in">＋</button><button type="button" data-zoom-input="fit">↗</button><button id="ivCropButton" type="button">⌗ ${tx('Crop Image', 'Cắt ảnh')}</button><button id="ivEditButton" type="button">✎ ${tx('Edit Pixels', 'Chỉnh pixel')}</button></div></div>
        <div class="iv-preview iv-input-preview"><div id="ivInputEmpty" class="iv-empty"><div class="iv-empty-icon">↑</div><strong>${tx('Upload an image', 'Tải ảnh lên')}</strong><span>${tx('PNG, JPG, JPEG, BMP or WebP · drag and drop supported', 'PNG, JPG, JPEG, BMP hoặc WebP · hỗ trợ kéo thả')}</span></div><canvas id="ivInputCanvas"></canvas><label id="ivDrop" class="iv-drop"><span>＋ ${tx('Choose image', 'Chọn ảnh')}</span><input id="ivFile" type="file" accept="image/png,image/jpeg,image/bmp,image/webp,.png,.jpg,.jpeg,.bmp,.webp" /></label></div>
        <div id="ivCropControls" class="iv-floating-controls" hidden><strong>${tx('Crop image', 'Cắt ảnh')}</strong><label>X <output id="ivCropXValue">0%</output><input id="ivCropX" type="range" min="0" max="70" step="1" value="${settings.crop.x}" /></label><label>Y <output id="ivCropYValue">0%</output><input id="ivCropY" type="range" min="0" max="70" step="1" value="${settings.crop.y}" /></label><label>${tx('Width', 'Rộng')} <output id="ivCropWidthValue">100%</output><input id="ivCropWidth" type="range" min="20" max="100" step="1" value="${settings.crop.width}" /></label><label>${tx('Height', 'Cao')} <output id="ivCropHeightValue">100%</output><input id="ivCropHeight" type="range" min="20" max="100" step="1" value="${settings.crop.height}" /></label></div>
        <div id="ivEditControls" class="iv-floating-controls" hidden><strong>${tx('Edit pixels', 'Chỉnh pixel')}</strong><label>${tx('Brightness', 'Độ sáng')} <output id="ivBrightnessValue">100%</output><input id="ivBrightness" type="range" min="50" max="150" value="100" /></label><label>${tx('Contrast', 'Độ tương phản')} <output id="ivContrastValue">100%</output><input id="ivContrast" type="range" min="50" max="180" value="100" /></label><label>${tx('Saturation', 'Độ bão hòa')} <output id="ivSaturationValue">100%</output><input id="ivSaturation" type="range" min="0" max="180" value="100" /></label></div>
        <div class="iv-options-card"><div class="iv-tabbar"><button class="active" data-input-tab="palette">${tx('Color Palettes', 'Bảng màu')}</button><button data-input-tab="background">${tx('Background', 'Nền')}</button></div><div id="ivPalettePanel" class="iv-option-panel"><div class="iv-field-heading"><strong>${tx('Colors', 'Số màu')}: <output id="ivColorCountValue">${settings.colorCount}</output></strong><button id="ivCustomPaletteToggle" type="button" class="iv-link">✎ ${tx('Custom Palette', 'Bảng màu tùy chỉnh')}</button></div><div class="iv-color-scale" id="ivPaletteSwatches"></div><label class="iv-range-row"><span>${tx('Color count', 'Số lượng màu')} <output>${settings.colorCount}</output></span><input id="ivColorCount" type="range" min="2" max="12" value="${settings.colorCount}" /></label><div id="ivCustomPalette" class="iv-custom-palette" hidden><input id="ivCustomColor" type="color" value="${rgbHex(settings.customPalette[0])}" /><button id="ivAddCustomColor" type="button">＋ ${tx('Add color', 'Thêm màu')}</button><div id="ivCustomPaletteList"></div></div></div><div id="ivBackgroundPanel" class="iv-option-panel" hidden><div class="iv-background-grid"><button class="active" data-background="remove">${tx('Remove background', 'Xóa nền')}</button><button data-background="keep">${tx('Keep original', 'Giữ nền gốc')}</button><button data-background="solid">${tx('Solid color', 'Nền màu')}</button></div><label class="iv-color-input">${tx('Background color', 'Màu nền')}<input id="ivBackgroundColor" type="color" value="${rgbHex(settings.backgroundColor)}" /></label></div><label class="iv-check-row"><input id="ivEnhance" type="checkbox" ${settings.enhance ? 'checked' : ''} /><span>${tx('Enhance image with local AI-style cleanup', 'Tăng cường ảnh bằng xử lý nâng cao')}</span><em>BETA</em></label></div>
        <div class="iv-advanced-card"><div class="iv-advanced-label">${tx('Advanced Options', 'Tùy chọn nâng cao')}</div><div class="iv-advanced-tabs"><button class="active" data-input-advanced="quality">${tx('Quality Enhancement', 'Cải thiện chất lượng')}</button><button data-input-advanced="filters">${tx('Filters', 'Bộ lọc')}</button><button data-input-advanced="text">${tx('Text', 'Chữ')}</button></div><div id="ivQualityPanel" class="iv-advanced-panel"><div class="iv-control-grid"><label>${tx('Anti-aliasing', 'Khử răng cưa')}<select id="ivAntiAliasing"><option value="off">${tx('Off', 'Tắt')}</option><option value="smart" selected>${tx('Smart', 'Thông minh')}</option><option value="mid">${tx('Mid', 'Vừa')}</option></select></label><label>${tx('Noise reduction', 'Giảm nhiễu')}<select id="ivNoiseReduction"><option value="off">${tx('Off', 'Tắt')}</option><option value="low" selected>${tx('Low', 'Thấp')}</option><option value="high">${tx('High', 'Cao')}</option></select></label><label>${tx('Upscaling', 'Phóng lớn')}<select id="ivUpscaling"><option value="1" selected>Off</option><option value="2">200%</option></select></label></div></div><div id="ivFiltersPanel" class="iv-advanced-panel" hidden><label class="iv-range-row"><span>${tx('Brightness', 'Độ sáng')}<output id="ivFilterBrightnessValue">100%</output></span><input id="ivFilterBrightness" type="range" min="50" max="150" value="100" /></label><label class="iv-range-row"><span>${tx('Contrast', 'Độ tương phản')}<output id="ivFilterContrastValue">100%</output></span><input id="ivFilterContrast" type="range" min="50" max="180" value="100" /></label><label class="iv-range-row"><span>${tx('Saturation', 'Độ bão hòa')}<output id="ivFilterSaturationValue">100%</output></span><input id="ivFilterSaturation" type="range" min="0" max="180" value="100" /></label></div><div id="ivTextPanel" class="iv-advanced-panel" hidden><p class="iv-help">${tx('Text is preserved as clean vector contours when it is part of the imported artwork.', 'Chữ trong ảnh được giữ thành đường vector sạch khi là một phần của hình nhập vào.')}</p></div></div>
      </section>
      <section class="iv-pane iv-output-pane">
        <div class="iv-pane-toolbar"><div class="iv-pane-title"><span class="iv-pane-icon">↗</span><strong>${tx('Output', 'Đầu ra')}</strong><small id="ivOutputStats">${tx('Waiting for input', 'Đang chờ ảnh')}</small></div><div class="iv-toolbar-actions"><button type="button" data-zoom-output="out">−</button><button type="button" data-zoom-output="in">＋</button><button type="button" data-zoom-output="fit">↗</button><button id="ivCopyButton" type="button">▣ ${tx('Copy SVG', 'Sao chép SVG')}</button><select id="ivDownloadFormat" aria-label="Download format"><option value="svg">SVG</option><option value="png">PNG</option><option value="json">JSON</option></select><button id="ivDownloadButton" type="button" class="iv-download">↓ ${tx('Download', 'Tải xuống')}</button></div></div>
        <div class="iv-preview iv-output-preview"><div id="ivOutputEmpty" class="iv-empty"><div class="iv-empty-icon">◇</div><strong>${tx('Your vector will appear here', 'Vector sẽ xuất hiện ở đây')}</strong><span>${tx('Upload an image to start vectorization.', 'Tải ảnh lên để bắt đầu chuyển vector.')}</span></div><div id="ivOutputPreview"></div></div>
        <div class="iv-options-card iv-output-card"><div class="iv-tabbar"><button class="active" data-output-mode="groups">${tx('Color Groups', 'Nhóm màu')}</button><button data-output-mode="gradients">${tx('Gradients', 'Gradient')}</button></div><div class="iv-output-colors"><div class="iv-field-heading"><strong>${tx('Colors', 'Số màu')}: <output id="ivOutputColorCount">0</output></strong><span id="ivOutputPathCount" class="iv-help">0 paths</span></div><div class="iv-color-scale" id="ivOutputColors"></div></div></div>
        <div class="iv-advanced-card iv-output-advanced"><div class="iv-advanced-label">${tx('Advanced Options', 'Tùy chọn nâng cao')}</div><div class="iv-advanced-tabs"><button class="active" data-output-advanced="vector">${tx('Vectorization', 'Vector hóa')}</button><button data-output-advanced="size">${tx('Output Size', 'Kích thước')}</button><button data-output-advanced="specials">${tx('Specials', 'Nâng cao')}</button><button data-output-advanced="limit">≤15KB GT</button></div><div id="ivVectorPanel" class="iv-advanced-panel"><label class="iv-range-row"><span>${tx('Roundness', 'Độ tròn')}<output id="ivRoundnessValue">45%</output></span><input id="ivRoundness" type="range" min="0" max="100" value="45" /></label><div class="iv-control-grid"><label>${tx('Minimum area', 'Diện tích tối thiểu')}<select id="ivMinimumArea"><option value="all">0px²</option><option value="small" selected>5px²</option><option value="large">90px²</option></select></label><label>${tx('Overlap', 'Chồng lấn')}<select id="ivOverlap"><option value="full">${tx('Full', 'Đầy đủ')}</option><option value="high" selected>${tx('High', 'Cao')}</option><option value="medium">${tx('Medium', 'Vừa')}</option></select></label></div><label class="iv-check-row"><input id="ivCircleDetection" type="checkbox" /><span>${tx('Circle detection', 'Nhận diện hình tròn')}</span></label></div><div id="ivSizePanel" class="iv-advanced-panel" hidden><label class="iv-range-row"><span>${tx('Longest side', 'Cạnh dài nhất')}<output id="ivOutputSizeValue">${settings.outputWidthMm} mm</output></span><input id="ivOutputSize" type="range" min="20" max="500" value="${settings.outputWidthMm}" /></label><p class="iv-help">${tx('The aspect ratio is preserved automatically.', 'Tự động giữ nguyên tỷ lệ khung hình.')}</p></div><div id="ivSpecialsPanel" class="iv-advanced-panel" hidden><label class="iv-check-row"><input id="ivAddOutline" type="checkbox" /><span>${tx('Add outline stroke', 'Thêm đường viền')}</span></label><label class="iv-range-row"><span>${tx('Outline width', 'Độ dày viền')}<output id="ivOutlineWidthValue">0.5</output> mm</span><input id="ivOutlineWidth" type="range" min="0.1" max="2" step="0.1" value="0.5" /></label></div><div id="ivLimitPanel" class="iv-advanced-panel" hidden><label class="iv-check-row"><input id="ivMaxFileSize" type="checkbox" /><span>${tx('Optimize SVG for smaller file size', 'Tối ưu SVG để giảm dung lượng')}</span></label><p class="iv-help">${tx('Uses shorter coordinates and simplified contours.', 'Dùng tọa độ ngắn hơn và contour đơn giản hơn.')}</p></div></div>
        <div class="iv-bottom-bar"><span id="ivStatus">${tx('Ready', 'Sẵn sàng')}</span><div><button id="ivReset" type="button" class="iv-secondary">↺ ${tx('Reset', 'Đặt lại')}</button><button id="ivDownloadSvg" type="button" class="iv-primary">↓ ${tx('Download SVG', 'Tải SVG')}</button></div></div>
      </section>
    </main>
  </div>`;
}
